esphome:
  name: sdspi_test
  platform: ESP32
  board: esp32dev

external_components:
  - source: local
    path: components

logger:

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASS"

# If needed, enable IDF-style framework or ensure you're not forcing arduino
# esphome:
#   platformio_options:
#     framework: idf

sdspi_card:
  id: my_sd
  cs_pin: GPIO5
  sclk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

# You can then use lambdas etc to call list_root, etc
# Example using on_boot
time:
  - platform: sntp
    id: my_time

on_boot:
  then:
    - lambda: |-
        id(my_sd)->dump_config();
        id(my_sd)->list_root();

sensor:
  - platform: sd_spi_card
    type: used_space
    unit_of_measurement: Mb
    name: "SD card used space"
    filters:
      - lambda: return sd_spi_card::convertBytes(x, sd_spi_card::MemoryUnits::MegaByte);

  - platform: sd_spi_card
    type: total_space
    unit_of_measurement: Gb
    name: "SD card total space"
    filters:
      - lambda: return sd_spi_card::convertBytes(x, sd_spi_card::MemoryUnits::GigaByte);

  - platform: sd_spi_card
    type: free_space
    unit_of_measurement: Gb
    name: "SD card free space"
    filters:
      - lambda: return sd_spi_card::convertBytes(x, sd_spi_card::MemoryUnits::GigaByte);

  - platform: sd_spi_card
    type: file_size
    name: "text.txt size"
    unit_of_measurement: Kb
    path: "/test.txt"
    filters:
      - lambda: return sd_spi_card::convertBytes(x, sd_spi_card::MemoryUnits::KiloByte);

text_sensor:
  - platform: sd_spi_card
    sd_card_type:
      name: "SD card type"


interval:
  - interval: 2s
    then:
      - lambda: |-
          static int counter = 0;
          auto ts = id(sntp_time).now().strftime("%FT%H-%M-%S");
          std::string line = std::string(ts) + "," + std::to_string(counter++) + "\n";
          std::vector<uint8_t> data(line.begin(), line.end());
          id(sd_spi).append_line("/log.csv", line);
      - logger.log: "Added CSV row to log.csv"
