esphome:
  name: sdspi_test
  platform: ESP32
  board: esp32dev

external_components:
  - source: local
    path: components

logger:

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASS"

# If needed, enable IDF-style framework or ensure you're not forcing arduino
# esphome:
#   platformio_options:
#     framework: idf

sdspi_card:
  id: my_sd
  cs_pin: GPIO5
  sclk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

# You can then use lambdas etc to call list_root, etc
# Example using on_boot
time:
  - platform: sntp
    id: my_time

on_boot:
  then:
    - lambda: |-
        id(my_sd)->dump_config();
        id(my_sd)->list_root();
